### ISSUE TITLE
Clicking in output window should put cursor in REPLet input line

### ISSUE THREAD

**Issue by Kebap** [demonnic/REPLet#3]
1. Open Replet
2. Click on some other program
3. Click on Replet output area
4. The cursor will be in Mudlet main input line

The cursor should go to Replet input line instead.

Noted on Windows with Replet v1.1.1

**Comment by demonnic** [comment]
The REPLet input line is just the command line for the UserWindow being enabled, I dunno if there's anything I can do about that in my package itself. May be something we need to look into in Mudlet itself.

**Comment by Kebap** [comment]
raised upstream
